### ISSUE TITLE
Please clarify - just colour, or all formatting attributes?

### ISSUE THREAD

**Issue by leonerd** [jcs/no_color#20]
Your main document talks about "colour" a lot, but that's not the only formatting attribute used by software. What about the use of bold, underline, italics, reverse video, and so on..? Should those be controlled by the same variable too? Or are these permitted, just not colours?

**Comment by jcs** [comment]
I would say use your judgement as the software author.  If it's a full-screen curses application like a text editor, then it doesn't make sense to strip out all attributes because it would make the software difficult to use.  If it's a program that just prints text but bolds certain characters, then I would say `NO_COLOR` should make it not add those bold attributes.
