### ISSUE TITLE
NO_COLOR= should be treated the same as unset

### ISSUE THREAD

**Issue by asottile** [jcs/no_color#57]
following precedence from posix environment variables such as `LANG` where the empty string and unset are treated as the same value

this also provides further flexibility when you don't have the ability to unset a variable, only override it with another value (it would otherwise be impossible to re-enable `NO_COLOR` in this situation)

**Comment by jcs** [comment]
Unless you're going to change all of the software that already implements `NO_COLOR`, it's too late to change that behaviour.  Lots of implementations already just check for the presence of the variable and don't check whether its value is an empty string (which was intentional, to make it easier to implement).

**Comment by asottile** [comment]
I'd suggest a 2.0 then which makes an adjustment in behavior. To intentionally differ from well established conventions seems not a good idea, especially POSIX

**Comment by madscientist** [comment]
I have to with this issue: it's a shame when a great idea for new standard behavior suffers from a critical issue with the design like this.  It's a clear anti-pattern to treat "unset" and "set but empty" environment variables differently except in very unusual situations (I can't think of one, actually, but I suppose they exist).  One extra term in the description ("non-empty") is all it would take to avoid this problem.

Requiring the variable to be unset makes the implementation _**very** marginally_ simpler in that you don't have to perform one extra check that the returned string is not empty (you need to write **(var && var[0] != '\0')** instead of just **(var)**, in C/C++), but at the same time it makes the _USAGE_ of this facility vastly more annoying and complicated.  There are obviously hundreds of times more users of this than there are implementers so the requirements should be targeted at making users' lives simpler.

Suppose users set `export NO_COLOR=true`, to avoid color in almost all cases.  What if we wanted to allow just a single utility to provide colorization?  If we require non-empty values it's trivial; for a one-time case:
```
$ NO_COLOR= myutility
```
or if we always wanted it to run that way:
```
alias myutility='NO_COLOR= command myutility'
```

If we have to actually unset the variable, there's no way to do it without creating a new process: either writing a shell function that invokes a sub-shell, or a shell script, or using non-standard behavior of **env**, such as:
```
myutility () { ( unset NO_COLOR; command myutility "$@" ); }
```
or
```
#!/bin/sh
unset NO_COLOR
/full/path/to/myutility "$@"
```
or
```
alias myutility='env -u NO_COLOR myutility'
```
(note that **env -u** is not standard and may not work on all systems)

I think that this issue should be re-opened and an update issued on the website.  Yes, there are many applications that already do things the "wrong" way but that shouldn't prevent us from making improvements: issues can be filed against those applications to get them updated.

It's also possible some users might have written `export NO_COLOR=` in their shell setup; they would have to change to `export NO_COLOR=1` or something.  Personally I suspect most users already set the variable to some value, rather than empty, but in any event setting to a value would allow it to work with all apps.

**Comment by lukeed** [comment]
Agree here. Nearly anything else treats `FOO=` and `FOO=0` as false flags. This is the first/only ENV I've encountered that doesn't align with that expectation. The points mentioned in #83 help illustrate the problems of `NO_COLOR=`.
